# Application Name
spring.application.name=Employee Management System

# PostgreSQL Database Settings
spring.datasource.url=jdbc:postgresql://dpg-d6g171p5pdvs73c76cng-a/springboot_backend_z6l1
spring.datasource.username=springboot_backend_z6l1_user
spring.datasource.password=SBiUL4mxeG6v7YABTMTsxQp9mQ2sDUqu
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Upload directory for profile images (filesystem path)
app.upload.dir=uploads

# Cross-Site Cookie Configuration (Required for Vercel -> Render)
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
