# Application Name
spring.application.name=Employee Management System

# MySQL Database Settings
spring.datasource.url=jdbc:postgresql://dpg-d6g171p5pdvs73c76cng-a/springboot_backend_z6l1
spring.datasource.username=springboot_backend_z6l1_user
spring.datasource.password=SBiUL4mxeG6v7YABTMTsxQp9mQ2sDUqu
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Upload directory for profile images (filesystem path)
app.upload.dir=uploads
